version: 2
jobs:
  build:
    branches:
      only:
        - master
    docker:
      - image: node:16
    steps:
      - add_ssh_keys:
          fingerprints:
            - "e9:db:42:34:df:58:3d:ba:9b:16:b3:61:6a:52:6f:73"
      - checkout
      - run: npm ci
      - run: npx react-scripts build
      - deploy:
          name: Deploy to gh-pages
          command: |
            git config --global user.email $GIT_EMAIL
            git config --global user.name $GIT_USER
            git clone $CIRCLE_REPOSITORY_URL out
            cd out
            git checkout gh-pages || git checkout --orphan gh-pages
            git rm -rf .
            cd ..
            cp -a build/. out/.
            mkdir -p out/.circleci && cp -a .circleci/. out/.circleci/.
            cd out
            git add -A
            git commit -m "deploy ${CIRCLE_SHA1}" --allow-empty
            git push origin gh-pages
