name: Build test

on:
  workflow_dispatch:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build-and-test:
    concurrency: ci-${{ github.ref }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2

      - name: Use Node.js 16.x 🐧
        uses: actions/setup-node@v2
        with:
          node-version: 16.x

      - name: Build and test 🔧
        env:
          DISABLE_ESLINT_PLUGIN: true
          TSC_COMPILE_ON_ERROR: true
        run: |
          npm ci
          npm run build
          npm run coverage

      - name: Run ESLint and TypeScript checks 🚨
        run: |
          npm install @microsoft/eslint-formatter-sarif@2.1.7
          npx eslint src --format @microsoft/eslint-formatter-sarif --output-file eslint-results.sarif
          npx tsc --project .

      - name: Upload code coverage 🚀
        if: always()
        uses: codecov/codecov-action@v3
        with:
#          fail_ci_if_error: true
          verbose: true
          version: "v0.1.15"
          token: ${{ secrets.CODECOV_TOKEN }}

      - name: Upload analysis results to GitHub 🚀
        if: always()
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: eslint-results.sarif
          wait-for-processing: true
